import Head from "next/head";
import Dashboard from "../components/Dashboard";
import Navbar from "../components/Navbar";
import Sidebar from "../components/Sidebar";

export default function Home() {
	return (
		<div className="">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="flex fixed top-5 left-5 bottom-5 right-0">
				<Sidebar />
				<div className="w-full md:w-[calc(100%_-_288px)] mx-5">
					<Navbar />
					<Dashboard />
				</div>
			</div>
		</div>
	);
}
